#!/usr/bin/env python
import sys
import os
import subprocess

if len(sys.argv) == 1:
    raise ValueError("Must provide a version number")

version = sys.argv[1]

setup_file = f"""
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="arc-cli",
    version="{version}",
    license="MIT",
    author="Sean Collings",
    author_email="sean@seanrcollings.com",
    description="A Regular CLI",
    long_description=long_description,
    long_description_content_type="text/markdown",
    download_url=f"https://github.com/seanrcollings/arc/archive/v{version}.tar.gz",
    url="https://github.com/seanrcollings/arc",
    keywords=["CLI", "extendable", "easy"],
    packages=setuptools.find_packages("src"),
    package_dir={{"": "src"}},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
"""

with open("./setup.py", "w") as file:
    file.write(setup_file)

username = os.getenv("PYPI_USERNAME")
if not username:
    raise ValueError("PYPI_USERNAME not set")

password = os.getenv("PYPI_PASSWORD")
if not password:
    raise ValueError("PYPI_PASSWORD not set")

subprocess.run(["python", "setup.py", "sdist"], check=True)
subprocess.run(
    ["twine", "upload", "dist/*", "--username", username, "--password", password,],
    check=True,
)
