site_name: arc
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings
  - awesome-pages
watch: [../arc, examples]
repo_url: https://github.com/seanrcollings/arc
repo_name: seanrcollings/arc
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Usage:
      - Intro: usage/intro.md
      - Command Parameters:
          - Parameters Intro: usage/parameters/intro.md
          - Arguments: usage/parameters/arguments.md
          - Options: usage/parameters/options.md
          - Flags: usage/parameters/flags.md
          - Counter: usage/parameters/counter.md
          - Parameter Types:
              - Types Intro: usage/parameters/types/types-intro.md
              - Supported Types: usage/parameters/types/supported-types.md
              - Type Middleware: usage/parameters/types/type-middleware.md
              - Type Arguments: usage/parameters/types/type-arguments.md
              - Custom Types: usage/parameters/types/custom-types.md
          - Parameter Sources: usage/parameters/sources.md
          - Parameter Groups: usage/parameters/groups.md
          - Dependency Injection: usage/parameters/dependancy-injection.md
      - Printing Output:
          - Intro: usage/presentation/presentation-intro.md
          - Printing: usage/presentation/printing.md
          - Coloring: usage/presentation/coloring.md
          - Rich Output: usage/presentation/rich-output.md
      - User Input: usage/user-input.md
      - Subcommands: usage/subcommands.md
      - Documentation Generation: usage/documentation-generation.md
      - Classful Commands: usage/classful-commands.md
      - Middleware: usage/middleware.md
      - Command State: usage/command-state.md
      - Plugins: usage/plugins.md
      - Shell Completions: usage/shell-completions.md
  - ...
