site_name: arc
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings
watch: [../arc, examples]
repo_url: https://github.com/seanrcollings/arc
repo_name: seanrcollings/arc
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Usage:
      - Intro: usage/intro.md
      - Printing & Coloring Output: usage/printing.md
      - Command Parameters:
          - Parameters Intro: usage/parameters/parameters-intro.md
          - Arguments: usage/parameters/arguments.md
          - Options: usage/parameters/options.md
          - Flags: usage/parameters/flags.md
          - Parameter Groups: usage/parameters/parameter-groups.md
      - Subcommands: usage/subcommands.md
      - Paramater Types: usage/parameter-types.md
      - Multiple Values: usage/multiple-values.md
      - Documentation Generation: usage/documentation-generation.md
      - Command Decorators: usage/decorators.md
      - Error Handlers: usage/error-handlers.md
      - Command State: usage/command-state.md
  - Advanced Usage:
      - Type Middleware: advanced-usage/type-middleware.md
      - Custom Types: advanced-usage/custom-types.md
      - Parameter Sources: advanced-usage/parameter-sources.md
      - Command Autoloading: advanced-usage/command-autoloading.md
      - Shell Completions: advanced-usage/shell-completions.md
  - Examples:
      - Grep Clone: examples/grep-clone.md
  - Reference:
      - arc.config: reference/config.md
      - arc.color: reference/color.md
      - arc.params: reference/params.md
      - arc.types:
          - transforms: reference/transforms.md
          - validators: reference/validators.md
          - file: reference/types/file.md
      - arc.command: reference/command.md
  - Changelog: changelog.md
