site_name: arc
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings
  - awesome-pages
watch: [../arc, examples]
repo_url: https://github.com/seanrcollings/arc
repo_name: seanrcollings/arc
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Usage:
      - Intro: usage/intro.md
      - Command Parameters:
          - Parameters Intro: usage/parameters/parameters-intro.md
          - Arguments: usage/parameters/arguments.md
          - Options: usage/parameters/options.md
          - Flags: usage/parameters/flags.md
          - Counter: usage/parameters/counter.md
          - Parameter Sources: usage/parameters/parameter-sources.md
          - Parameter Groups: usage/parameters/parameter-groups.md
          - Parameter Types:
              - Types Intro: usage/parameters/parameter-types/types-intro.md
              - Supported Types: usage/parameters/parameter-types/supported-types.md
              - Multiple Values: usage/parameters/parameter-types/multiple-values.md
              - Type Middleware: usage/parameters/parameter-types/type-middleware.md
              - Custom Types: usage/parameters/parameter-types/custom-types.md
      - Printing & Coloring Output: usage/printing.md
      - Subcommands: usage/subcommands.md
      - File Access: usage/file-access.md
      - Documentation Generation: usage/documentation-generation.md
      - Middleware: usage/middleware.md
      - Command State: usage/command-state.md
  - Advanced Usage:
      - Using Context: advanced-usage/using-context.md
      - Command Autoloading: advanced-usage/command-autoloading.md
      - Shell Completions: advanced-usage/shell-completions.md
      - Dependency Injection: advanced-usage/dependency-injection.md
  - ...
