name: deploy-docs

on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Setup
        run: poetry run bin/ctl build docs
      - name: Deploy
        working-directory: ./docs
        run: poetry run mkdocs gh-deploy --force
