name: Deploy Docs

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Setup
        run: uv run python bin/ctl build docs
      - name: Deploy
        working-directory: ./docs
        run: uv run mkdocs gh-deploy --force
